project:
  type: book
  output-dir: docs

book:
  title: "CTS ETL Methodology"
  favicon: "/media/Aplus_A_only_blue.png"
  author: "Emma Spielfogel"
  date: today
  navbar:
    logo: "/media/Aplus_A_only_blue.png"
  chapters:
    - index.qmd
    - rstudio-setup.qmd
    - oracle-setup.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
    number-depth: 3
    code-fold: show
  pdf:
    documentclass: scrreprt
    number-depth: 3

editor: visual